### ISSUE TITLE
Config folder filled with game files

### ISSUE THREAD

**Issue by ThaChillera** [ropenttd/docker_openttd#3]
my docker run command is:
`docker run -d --name openttd --restart=always -p 3979:3979/tcp -p 3979:3979/udp -e savegame=autosave -v ~/.openttd:/config:rw redditopenttd/openttd:latest`

It runs fine, but instead of ~/.openttd having just a config file in it, it contains the base game files. screenshot: https://i.imgur.com/dyXPnrb.png

Is this intended? I can't find openttd.cfg anywhere, and it doesn't seem like this is intended.

**Comment by luaduck** [comment]
The start script should call the game quickly to make a config file, as per this line:

https://github.com/ropenttd/docker_openttd/blob/089ef0e4b2f9c4d8f51218e76d967a74182d3db2/entrypoint.sh#L8-L13

(it's a little hacky, but this has worked in the past)

If this isn't working, then there's one of two problems:

1. It's never worked (fairly likely, though I'm fairly sure I did test this)
2. There's been a change in a recent OpenTTD version that changes how config auto-generation worked

An option for fixing this would be to ship our own default `openttd.cfg`, but this feels unclean because config variables can (and do) change between versions, and we'd have to keep on top of that.

As for the base game files being inside the config directory, you may want to experiment with mounting explicit files as required (do something like `-v ~/.openttd/openttd.cfg:/config/openttd.cfg -v ~/.openttd/save:/config/save:rw` once you have one) - though note that if you want to add stuff to, say, `content_download`, you'll need to mount that as well. (I just mount the whole thing, mostly because I'm lazy). If this works for you, I can tweak the readme along those lines.

**Comment by ThaChillera** [comment]
I got a config file from somewhere, saved it and it mounted it as expected, so mounting it explicitly isn't necessary :) and mounting the base isn't an issue, just unexpected and caused me to be more confused, you might want to add it to the docker readme! Thanks for the help, let me know if you need help debugging/testing.

**Comment by luaduck** [comment]
Glad to hear that worked for you! I'll leave this open until I (or someone else) can figure out a better way of tackling the issue than making people bring their own config.

I'll tweak the readme ASARP.
